### model
model_name_or_path: /data/model/Llama-3.1-8B

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: q_proj,v_proj,k_proj,o_proj
lora_rank: 64
lora_alpha: 128

### dataset
dataset: poisoned_shadow_dataset
template: llama3
cutoff_len: 2048
max_samples: 500
overwrite_cache: true
preprocessing_num_workers: 32

### output
output_dir: /data/lora/stage1_poisoned
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
